cc_library(
    name = 'contract_convertor',
    srcs = [
        'c/ContractConvertor/ContractConvertor.c',
        'c/ContractConvertor/CtpContractConvertor.c',
        'c/ContractConvertor/CtpUtil.c',
        'c/ContractConvertor/EsunnyV3ContractConvertor.c',
        'c/ContractConvertor/EsunnyV3Util.c',
        'c/ContractConvertor/EsunnyV9ContractConvertor.c',
        'c/ContractConvertor/Util.c',
    ],
    export_incs = [
        'c/ContractConvertor',
    ]
)