/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.10
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.longsheng.xueqiao.contractconvertor.swig;

public final class SledCommodityType {
  public final static SledCommodityType SledCommodityType_NONE = new SledCommodityType("SledCommodityType_NONE", ContractConvertorJNI.SledCommodityType_NONE_get());
  public final static SledCommodityType SledCommodityType_FUTURES = new SledCommodityType("SledCommodityType_FUTURES", ContractConvertorJNI.SledCommodityType_FUTURES_get());
  public final static SledCommodityType SledCommodityType_OPTION = new SledCommodityType("SledCommodityType_OPTION", ContractConvertorJNI.SledCommodityType_OPTION_get());
  public final static SledCommodityType SledCommodityType_SPOT = new SledCommodityType("SledCommodityType_SPOT", ContractConvertorJNI.SledCommodityType_SPOT_get());
  public final static SledCommodityType SledCommodityType_SPREAD_MONTH = new SledCommodityType("SledCommodityType_SPREAD_MONTH", ContractConvertorJNI.SledCommodityType_SPREAD_MONTH_get());
  public final static SledCommodityType SledCommodityType_SPREAD_COMMODITY = new SledCommodityType("SledCommodityType_SPREAD_COMMODITY", ContractConvertorJNI.SledCommodityType_SPREAD_COMMODITY_get());
  public final static SledCommodityType SledCommodityType_BUL = new SledCommodityType("SledCommodityType_BUL", ContractConvertorJNI.SledCommodityType_BUL_get());
  public final static SledCommodityType SledCommodityType_BER = new SledCommodityType("SledCommodityType_BER", ContractConvertorJNI.SledCommodityType_BER_get());
  public final static SledCommodityType SledCommodityType_STD = new SledCommodityType("SledCommodityType_STD", ContractConvertorJNI.SledCommodityType_STD_get());
  public final static SledCommodityType SledCommodityType_STG = new SledCommodityType("SledCommodityType_STG", ContractConvertorJNI.SledCommodityType_STG_get());
  public final static SledCommodityType SledCommodityType_PRT = new SledCommodityType("SledCommodityType_PRT", ContractConvertorJNI.SledCommodityType_PRT_get());
  public final static SledCommodityType SledCommodityType_DIRECTFOREX = new SledCommodityType("SledCommodityType_DIRECTFOREX", ContractConvertorJNI.SledCommodityType_DIRECTFOREX_get());
  public final static SledCommodityType SledCommodityType_INDIRECTFOREX = new SledCommodityType("SledCommodityType_INDIRECTFOREX", ContractConvertorJNI.SledCommodityType_INDIRECTFOREX_get());
  public final static SledCommodityType SledCommodityType_CROSSFOREX = new SledCommodityType("SledCommodityType_CROSSFOREX", ContractConvertorJNI.SledCommodityType_CROSSFOREX_get());
  public final static SledCommodityType SledCommodityType_INDEX = new SledCommodityType("SledCommodityType_INDEX", ContractConvertorJNI.SledCommodityType_INDEX_get());
  public final static SledCommodityType SledCommodityType_STOCK = new SledCommodityType("SledCommodityType_STOCK", ContractConvertorJNI.SledCommodityType_STOCK_get());

  public final int swigValue() {
    return swigValue;
  }

  public String toString() {
    return swigName;
  }

  public static SledCommodityType swigToEnum(int swigValue) {
    if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
      return swigValues[swigValue];
    for (int i = 0; i < swigValues.length; i++)
      if (swigValues[i].swigValue == swigValue)
        return swigValues[i];
    throw new IllegalArgumentException("No enum " + SledCommodityType.class + " with value " + swigValue);
  }

  private SledCommodityType(String swigName) {
    this.swigName = swigName;
    this.swigValue = swigNext++;
  }

  private SledCommodityType(String swigName, int swigValue) {
    this.swigName = swigName;
    this.swigValue = swigValue;
    swigNext = swigValue+1;
  }

  private SledCommodityType(String swigName, SledCommodityType swigEnum) {
    this.swigName = swigName;
    this.swigValue = swigEnum.swigValue;
    swigNext = this.swigValue+1;
  }

  private static SledCommodityType[] swigValues = { SledCommodityType_NONE, SledCommodityType_FUTURES, SledCommodityType_OPTION, SledCommodityType_SPOT, SledCommodityType_SPREAD_MONTH, SledCommodityType_SPREAD_COMMODITY, SledCommodityType_BUL, SledCommodityType_BER, SledCommodityType_STD, SledCommodityType_STG, SledCommodityType_PRT, SledCommodityType_DIRECTFOREX, SledCommodityType_INDIRECTFOREX, SledCommodityType_CROSSFOREX, SledCommodityType_INDEX, SledCommodityType_STOCK };
  private static int swigNext = 0;
  private final int swigValue;
  private final String swigName;
}

