/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.common.thriftapi;

import org.apache.thrift.scheme.IScheme;
import org.apache.thrift.scheme.SchemeFactory;
import org.apache.thrift.scheme.StandardScheme;

import org.apache.thrift.scheme.TupleScheme;
import org.apache.thrift.protocol.TTupleProtocol;
import org.apache.thrift.protocol.TProtocolException;
import org.apache.thrift.EncodingUtils;
import org.apache.thrift.TException;
import org.apache.thrift.async.AsyncMethodCallback;
import org.apache.thrift.server.AbstractNonblockingServer.*;
import java.util.List;
import java.util.ArrayList;
import java.util.Map;
import java.util.HashMap;
import java.util.EnumMap;
import java.util.Set;
import java.util.HashSet;
import java.util.EnumSet;
import java.util.Collections;
import java.util.BitSet;
import java.nio.ByteBuffer;
import java.util.Arrays;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

public class ContractCTP implements org.apache.thrift.TBase<ContractCTP, ContractCTP._Fields>, java.io.Serializable, Cloneable, Comparable<ContractCTP> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ContractCTP");

  private static final org.apache.thrift.protocol.TField CONTRACT_BASE_FIELD_DESC = new org.apache.thrift.protocol.TField("contractBase", org.apache.thrift.protocol.TType.STRUCT, (short)1);
  private static final org.apache.thrift.protocol.TField CTP_EXTRA_FIELD_DESC = new org.apache.thrift.protocol.TField("ctpExtra", org.apache.thrift.protocol.TType.STRUCT, (short)2);

  private static final Map<Class<? extends IScheme>, SchemeFactory> schemes = new HashMap<Class<? extends IScheme>, SchemeFactory>();
  static {
    schemes.put(StandardScheme.class, new ContractCTPStandardSchemeFactory());
    schemes.put(TupleScheme.class, new ContractCTPTupleSchemeFactory());
  }

  public ContractBase contractBase; // optional
  public CTPContractExtra ctpExtra; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CONTRACT_BASE((short)1, "contractBase"),
    CTP_EXTRA((short)2, "ctpExtra");

    private static final Map<String, _Fields> byName = new HashMap<String, _Fields>();

    static {
      for (_Fields field : EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CONTRACT_BASE
          return CONTRACT_BASE;
        case 2: // CTP_EXTRA
          return CTP_EXTRA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    public static _Fields findByName(String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final String _fieldName;

    _Fields(short thriftId, String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private _Fields optionals[] = {_Fields.CONTRACT_BASE,_Fields.CTP_EXTRA};
  public static final Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CONTRACT_BASE, new org.apache.thrift.meta_data.FieldMetaData("contractBase", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ContractBase.class)));
    tmpMap.put(_Fields.CTP_EXTRA, new org.apache.thrift.meta_data.FieldMetaData("ctpExtra", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, CTPContractExtra.class)));
    metaDataMap = Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ContractCTP.class, metaDataMap);
  }

  public ContractCTP() {
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ContractCTP(ContractCTP other) {
    if (other.isSetContractBase()) {
      this.contractBase = new ContractBase(other.contractBase);
    }
    if (other.isSetCtpExtra()) {
      this.ctpExtra = new CTPContractExtra(other.ctpExtra);
    }
  }

  public ContractCTP deepCopy() {
    return new ContractCTP(this);
  }

  @Override
  public void clear() {
    this.contractBase = null;
    this.ctpExtra = null;
  }

  public ContractBase getContractBase() {
    return this.contractBase;
  }

  public ContractCTP setContractBase(ContractBase contractBase) {
    this.contractBase = contractBase;
    return this;
  }

  public void unsetContractBase() {
    this.contractBase = null;
  }

  /** Returns true if field contractBase is set (has been assigned a value) and false otherwise */
  public boolean isSetContractBase() {
    return this.contractBase != null;
  }

  public void setContractBaseIsSet(boolean value) {
    if (!value) {
      this.contractBase = null;
    }
  }

  public CTPContractExtra getCtpExtra() {
    return this.ctpExtra;
  }

  public ContractCTP setCtpExtra(CTPContractExtra ctpExtra) {
    this.ctpExtra = ctpExtra;
    return this;
  }

  public void unsetCtpExtra() {
    this.ctpExtra = null;
  }

  /** Returns true if field ctpExtra is set (has been assigned a value) and false otherwise */
  public boolean isSetCtpExtra() {
    return this.ctpExtra != null;
  }

  public void setCtpExtraIsSet(boolean value) {
    if (!value) {
      this.ctpExtra = null;
    }
  }

  public void setFieldValue(_Fields field, Object value) {
    switch (field) {
    case CONTRACT_BASE:
      if (value == null) {
        unsetContractBase();
      } else {
        setContractBase((ContractBase)value);
      }
      break;

    case CTP_EXTRA:
      if (value == null) {
        unsetCtpExtra();
      } else {
        setCtpExtra((CTPContractExtra)value);
      }
      break;

    }
  }

  public Object getFieldValue(_Fields field) {
    switch (field) {
    case CONTRACT_BASE:
      return getContractBase();

    case CTP_EXTRA:
      return getCtpExtra();

    }
    throw new IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new IllegalArgumentException();
    }

    switch (field) {
    case CONTRACT_BASE:
      return isSetContractBase();
    case CTP_EXTRA:
      return isSetCtpExtra();
    }
    throw new IllegalStateException();
  }

  @Override
  public boolean equals(Object that) {
    if (that == null)
      return false;
    if (that instanceof ContractCTP)
      return this.equals((ContractCTP)that);
    return false;
  }

  public boolean equals(ContractCTP that) {
    if (that == null)
      return false;

    boolean this_present_contractBase = true && this.isSetContractBase();
    boolean that_present_contractBase = true && that.isSetContractBase();
    if (this_present_contractBase || that_present_contractBase) {
      if (!(this_present_contractBase && that_present_contractBase))
        return false;
      if (!this.contractBase.equals(that.contractBase))
        return false;
    }

    boolean this_present_ctpExtra = true && this.isSetCtpExtra();
    boolean that_present_ctpExtra = true && that.isSetCtpExtra();
    if (this_present_ctpExtra || that_present_ctpExtra) {
      if (!(this_present_ctpExtra && that_present_ctpExtra))
        return false;
      if (!this.ctpExtra.equals(that.ctpExtra))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    return 0;
  }

  @Override
  public int compareTo(ContractCTP other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = Boolean.valueOf(isSetContractBase()).compareTo(other.isSetContractBase());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetContractBase()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.contractBase, other.contractBase);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = Boolean.valueOf(isSetCtpExtra()).compareTo(other.isSetCtpExtra());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCtpExtra()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ctpExtra, other.ctpExtra);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    schemes.get(iprot.getScheme()).getScheme().read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    schemes.get(oprot.getScheme()).getScheme().write(oprot, this);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder("ContractCTP(");
    boolean first = true;

    if (isSetContractBase()) {
      sb.append("contractBase:");
      if (this.contractBase == null) {
        sb.append("null");
      } else {
        sb.append(this.contractBase);
      }
      first = false;
    }
    if (isSetCtpExtra()) {
      if (!first) sb.append(", ");
      sb.append("ctpExtra:");
      if (this.ctpExtra == null) {
        sb.append("null");
      } else {
        sb.append(this.ctpExtra);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
    if (contractBase != null) {
      contractBase.validate();
    }
    if (ctpExtra != null) {
      ctpExtra.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, ClassNotFoundException {
    try {
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ContractCTPStandardSchemeFactory implements SchemeFactory {
    public ContractCTPStandardScheme getScheme() {
      return new ContractCTPStandardScheme();
    }
  }

  private static class ContractCTPStandardScheme extends StandardScheme<ContractCTP> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ContractCTP struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CONTRACT_BASE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.contractBase = new ContractBase();
              struct.contractBase.read(iprot);
              struct.setContractBaseIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // CTP_EXTRA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.ctpExtra = new CTPContractExtra();
              struct.ctpExtra.read(iprot);
              struct.setCtpExtraIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ContractCTP struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.contractBase != null) {
        if (struct.isSetContractBase()) {
          oprot.writeFieldBegin(CONTRACT_BASE_FIELD_DESC);
          struct.contractBase.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.ctpExtra != null) {
        if (struct.isSetCtpExtra()) {
          oprot.writeFieldBegin(CTP_EXTRA_FIELD_DESC);
          struct.ctpExtra.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ContractCTPTupleSchemeFactory implements SchemeFactory {
    public ContractCTPTupleScheme getScheme() {
      return new ContractCTPTupleScheme();
    }
  }

  private static class ContractCTPTupleScheme extends TupleScheme<ContractCTP> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ContractCTP struct) throws org.apache.thrift.TException {
      TTupleProtocol oprot = (TTupleProtocol) prot;
      BitSet optionals = new BitSet();
      if (struct.isSetContractBase()) {
        optionals.set(0);
      }
      if (struct.isSetCtpExtra()) {
        optionals.set(1);
      }
      oprot.writeBitSet(optionals, 2);
      if (struct.isSetContractBase()) {
        struct.contractBase.write(oprot);
      }
      if (struct.isSetCtpExtra()) {
        struct.ctpExtra.write(oprot);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ContractCTP struct) throws org.apache.thrift.TException {
      TTupleProtocol iprot = (TTupleProtocol) prot;
      BitSet incoming = iprot.readBitSet(2);
      if (incoming.get(0)) {
        struct.contractBase = new ContractBase();
        struct.contractBase.read(iprot);
        struct.setContractBaseIsSet(true);
      }
      if (incoming.get(1)) {
        struct.ctpExtra = new CTPContractExtra();
        struct.ctpExtra.read(iprot);
        struct.setCtpExtraIsSet(true);
      }
    }
  }

}

