/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.longsheng.xueqiao.util.esunny9.swig;

public interface EsunnyTradeSwigUtilConstants {
  public final static char ESUNNY9_COMMODITY_TYPE_NONE = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_NONE_get();
  public final static char ESUNNY9_COMMODITY_TYPE_SPOT = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_SPOT_get();
  public final static char ESUNNY9_COMMODITY_TYPE_FUTURES = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_FUTURES_get();
  public final static char ESUNNY9_COMMODITY_TYPE_OPTION = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_OPTION_get();
  public final static char ESUNNY9_COMMODITY_TYPE_SPREAD_MONTH = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_SPREAD_MONTH_get();
  public final static char ESUNNY9_COMMODITY_TYPE_SPREAD_COMMODITY = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_SPREAD_COMMODITY_get();
  public final static char ESUNNY9_COMMODITY_TYPE_BUL = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_BUL_get();
  public final static char ESUNNY9_COMMODITY_TYPE_BER = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_BER_get();
  public final static char ESUNNY9_COMMODITY_TYPE_STD = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_STD_get();
  public final static char ESUNNY9_COMMODITY_TYPE_STG = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_STG_get();
  public final static char ESUNNY9_COMMODITY_TYPE_PRT = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_PRT_get();
  public final static char ESUNNY9_COMMODITY_TYPE_DIRECTFOREX = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_DIRECTFOREX_get();
  public final static char ESUNNY9_COMMODITY_TYPE_INDIRECTFOREX = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_INDIRECTFOREX_get();
  public final static char ESUNNY9_COMMODITY_TYPE_CROSSFOREX = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_CROSSFOREX_get();
  public final static char ESUNNY9_COMMODITY_TYPE_INDEX = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_INDEX_get();
  public final static char ESUNNY9_COMMODITY_TYPE_STOCK = EsunnyTradeSwigUtilJNI.ESUNNY9_COMMODITY_TYPE_STOCK_get();
  public final static char ESUNNY9_CALLPUT_FLAG_CALL = EsunnyTradeSwigUtilJNI.ESUNNY9_CALLPUT_FLAG_CALL_get();
  public final static char ESUNNY9_CALLPUT_FLAG_PUT = EsunnyTradeSwigUtilJNI.ESUNNY9_CALLPUT_FLAG_PUT_get();
  public final static char ESUNNY9_CALLPUT_FLAG_NONE = EsunnyTradeSwigUtilJNI.ESUNNY9_CALLPUT_FLAG_NONE_get();
  public final static char ESUNNY9_CONTRACT_TYPE_TRADEQUOTE = EsunnyTradeSwigUtilJNI.ESUNNY9_CONTRACT_TYPE_TRADEQUOTE_get();
  public final static char ESUNNY9_CONTRACT_TYPE_QUOTE = EsunnyTradeSwigUtilJNI.ESUNNY9_CONTRACT_TYPE_QUOTE_get();
  public final static char ESUNNY9_CLOSE_MODE_NONE = EsunnyTradeSwigUtilJNI.ESUNNY9_CLOSE_MODE_NONE_get();
  public final static char ESUNNY9_CLOSE_MODE_UNFINISHED = EsunnyTradeSwigUtilJNI.ESUNNY9_CLOSE_MODE_UNFINISHED_get();
  public final static char ESUNNY9_CLOSE_MODE_OPENCOVER = EsunnyTradeSwigUtilJNI.ESUNNY9_CLOSE_MODE_OPENCOVER_get();
  public final static char ESUNNY9_CLOSE_MODE_CLOSETODAY = EsunnyTradeSwigUtilJNI.ESUNNY9_CLOSE_MODE_CLOSETODAY_get();
  public final static char ESUNNY9_CMB_DIRECT_FIRST = EsunnyTradeSwigUtilJNI.ESUNNY9_CMB_DIRECT_FIRST_get();
  public final static char ESUNNY9_CMB_DIRECT_SECOND = EsunnyTradeSwigUtilJNI.ESUNNY9_CMB_DIRECT_SECOND_get();
  public final static char ESUNNY9_DELIVERY_MODE_GOODS = EsunnyTradeSwigUtilJNI.ESUNNY9_DELIVERY_MODE_GOODS_get();
  public final static char ESUNNY9_DELIVERY_MODE_CASH = EsunnyTradeSwigUtilJNI.ESUNNY9_DELIVERY_MODE_CASH_get();
  public final static char ESUNNY9_DELIVERY_MODE_EXECUTE = EsunnyTradeSwigUtilJNI.ESUNNY9_DELIVERY_MODE_EXECUTE_get();
  public final static char ESUNNY9_DELIVERY_MODE_ABANDON = EsunnyTradeSwigUtilJNI.ESUNNY9_DELIVERY_MODE_ABANDON_get();
  public final static char ESUNNY9_DELIVERY_MODE_HKF = EsunnyTradeSwigUtilJNI.ESUNNY9_DELIVERY_MODE_HKF_get();
  public final static char ESUNNY9_YNFLAG_YES = EsunnyTradeSwigUtilJNI.ESUNNY9_YNFLAG_YES_get();
  public final static char ESUNNY9_YNFLAG_NO = EsunnyTradeSwigUtilJNI.ESUNNY9_YNFLAG_NO_get();
}
