/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.es_service.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EsCoverModeType implements org.apache.thrift.TEnum {
  UNKNOWN(-1),
  COVER_MODE_NONE(0),
  COVER_MODE_UNFINISHED(1),
  COVER_MODE_OPENCOVER(2),
  COVER_MODE_COVERTODAY(3);

  private final int value;

  private EsCoverModeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EsCoverModeType findByValue(int value) { 
    switch (value) {
      case -1:
        return UNKNOWN;
      case 0:
        return COVER_MODE_NONE;
      case 1:
        return COVER_MODE_UNFINISHED;
      case 2:
        return COVER_MODE_OPENCOVER;
      case 3:
        return COVER_MODE_COVERTODAY;
      default:
        return null;
    }
  }
}
