/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.es_service.thrift;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum EsOrderWayType implements org.apache.thrift.TEnum {
  UNKNOWN(-1),
  ORDER_WAY_SELF_ETRADER(0),
  ORDER_WAY_PROXY_ETRADER(1),
  ORDER_WAY_JTRADER(2),
  ORDER_WAY_MANUAL(3),
  ORDER_WAY_CARRY(4),
  ORDER_WAY_PROGRAM(5);

  private final int value;

  private EsOrderWayType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static EsOrderWayType findByValue(int value) { 
    switch (value) {
      case -1:
        return UNKNOWN;
      case 0:
        return ORDER_WAY_SELF_ETRADER;
      case 1:
        return ORDER_WAY_PROXY_ETRADER;
      case 2:
        return ORDER_WAY_JTRADER;
      case 3:
        return ORDER_WAY_MANUAL;
      case 4:
        return ORDER_WAY_CARRY;
      case 5:
        return ORDER_WAY_PROGRAM;
      default:
        return null;
    }
  }
}
