/**
 * Autogenerated by Thrift Compiler (0.9.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.longsheng.xueqiao.ctp_service.thriftapi;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum CtpCloseDealTypeType implements org.apache.thrift.TEnum {
  THOST_FTDC_CDT_Normal(0),
  THOST_FTDC_CDT_SpecFirst(1);

  private final int value;

  private CtpCloseDealTypeType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static CtpCloseDealTypeType findByValue(int value) { 
    switch (value) {
      case 0:
        return THOST_FTDC_CDT_Normal;
      case 1:
        return THOST_FTDC_CDT_SpecFirst;
      default:
        return null;
    }
  }
}
